"use client"

/**
 * LabelPrintDialog — shared product-label printing dialog for web + desktop.
 *
 * Shows a live preview of the label (from the SAME shared markup that prints),
 * a copies stepper, and two actions:
 *   - Print        → onPrint(html)     (browser print dialog / native)
 *   - Download PDF → onDownloadPdf(html) (jsPDF html(), per-app)
 *
 * The HTML is generated by @munim/core's `renderLabelSheetHtml` — one model,
 * so the preview, the printed sheet and the PDF are always identical.
 */
import * as React from "react";
import { Printer, FileDown, Minus, Plus, Tag } from "lucide-react";
import { renderLabelMarkup, renderLabelSheetHtml, type ProductLabel } from "@munim/core";
import { cn } from "../lib/utils";
import { Button } from "./button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "./dialog";

export function LabelPrintDialog({
  open,
  onOpenChange,
  labels,
  copies,
  onCopiesChange,
  onPrint,
  onDownloadPdf,
  busy,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  labels: ProductLabel[];
  copies: number;
  onCopiesChange: (copies: number) => void;
  /** Called with the full sheet HTML for the browser print dialog. */
  onPrint: (html: string) => void;
  /** Called with the full sheet HTML for PDF generation (jsPDF). */
  onDownloadPdf: (html: string) => void;
  busy?: boolean;
}) {
  const [previewIndex, setPreviewIndex] = React.useState(0);

  React.useEffect(() => {
    if (open) setPreviewIndex(0);
  }, [open]);

  const first = labels[previewIndex] ?? labels[0];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <Tag className="h-5 w-5" />
            </div>
            <div>
              <DialogTitle>Print product labels</DialogTitle>
              <DialogDescription>
                {labels.length} label{labels.length !== 1 ? "s" : ""} · {copies} copy
                {copies !== 1 ? "ies" : ""} · 24-up A4 sheet (63.5 × 33.9 mm each)
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <div className="space-y-4">
          {/* Label preview — the exact markup that prints, slightly scaled. */}
          <div className="flex items-center justify-center rounded-lg border bg-muted/40 p-4">
            <div className="overflow-hidden rounded-md bg-white shadow-sm" style={{ width: "240px", height: "128px" }}>
              {first ? (
                <div
                  style={{ transform: "scale(0.99)", transformOrigin: "top left", width: "240px", height: "128px" }}
                  dangerouslySetInnerHTML={{ __html: renderLabelMarkup(first) }}
                />
              ) : (
                <div className="flex h-full items-center justify-center text-xs text-muted-foreground">
                  No label data
                </div>
              )}
            </div>
          </div>

          {labels.length > 1 && (
            <div className="flex items-center justify-center gap-1.5">
              {labels.map((l, i) => (
                <button
                  key={l.productId}
                  type="button"
                  onClick={() => setPreviewIndex(i)}
                  title={l.productName}
                  className={cn(
                    "h-2 w-6 rounded-full transition-colors",
                    i === previewIndex ? "bg-primary" : "bg-muted hover:bg-muted-foreground/40",
                  )}
                  aria-label={`Preview label ${i + 1}`}
                />
              ))}
            </div>
          )}

          {/* Copies stepper */}
          <div className="flex items-center justify-between rounded-lg border p-3">
            <div>
              <p className="text-sm font-medium">Number of copies</p>
              <p className="text-xs text-muted-foreground">
                Each copy adds one physical label to the sheet.
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="icon"
                className="h-8 w-8"
                onClick={() => onCopiesChange(Math.max(1, copies - 1))}
                disabled={copies <= 1}
                aria-label="Fewer copies"
              >
                <Minus className="h-4 w-4" />
              </Button>
              <span className="w-10 text-center text-sm font-semibold tabular-nums">{copies}</span>
              <Button
                variant="outline"
                size="icon"
                className="h-8 w-8"
                onClick={() => onCopiesChange(Math.min(100, copies + 1))}
                disabled={copies >= 100}
                aria-label="More copies"
              >
                <Plus className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button
            variant="outline"
            onClick={() => onPrint(renderLabelSheetHtmlFor(labels, copies))}
            disabled={busy || labels.length === 0}
          >
            <Printer className="h-4 w-4" /> Print
          </Button>
          <Button
            onClick={() => onDownloadPdf(renderLabelSheetHtmlFor(labels, copies))}
            disabled={busy || labels.length === 0}
          >
            <FileDown className="h-4 w-4" /> Download PDF
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function renderLabelSheetHtmlFor(labels: ProductLabel[], copies: number): string {
  return renderLabelSheetHtml(labels, { copies });
}
