"use client"

/**
 * LabelPrintDialog — shared product-label printing dialog for web + desktop.
 *
 * Shows a live preview of the label (from the SAME shared markup that prints),
 * a copies stepper, and two actions:
 *   - Print        → onPrint(html)     (browser print dialog / native)
 *   - Download PDF → onDownloadPdf(html) (jsPDF html(), per-app)
 *
 * Desktop additionally passes `directPrint`, which adds silent raw printing
 * to a thermal label printer (TSC TE244 etc.): the app builds TSPL2 commands
 * from the same `ProductLabel` model and spools them straight to the device —
 * no print dialog. Web (browser sandbox) simply omits the prop.
 *
 * The HTML is generated by @munim/core's `renderLabelSheetHtml` — one model,
 * so the preview, the printed sheet and the PDF are always identical.
 */
import * as React from "react";
import { Printer, FileDown, Minus, Plus, Tag, RefreshCw, Usb, ChevronDown, ChevronUp, RotateCcw } from "lucide-react";
import {
  renderLabelSheetHtml,
  DEFAULT_LABEL_PRINT_SETTINGS,
  type LabelPrinterInfo,
  type LabelPrintSettings,
  type ProductLabel,
} from "@munim/core";
import { cn } from "../lib/utils";
import { Button } from "./button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "./dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./select";

/** Host-provided bridge for direct thermal printing (desktop only). */
export type DirectLabelPrint = {
  printers: LabelPrinterInfo[];
  selected: string | undefined;
  onSelect: (name: string) => void;
  onPrint: (settings: LabelPrintSettings) => void;
  onRefresh: () => void;
  loading?: boolean;
  busy?: boolean;
  error?: string | null;
  savedSettings: LabelPrintSettings;
  onSaveSettings: (settings: LabelPrintSettings) => void;
};

export function LabelPrintDialog({
  open,
  onOpenChange,
  labels,
  copies,
  onCopiesChange,
  onPrint,
  onDownloadPdf,
  directPrint,
  busy,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  labels: ProductLabel[];
  copies: number;
  onCopiesChange: (copies: number) => void;
  /** Called with the full sheet HTML for the browser print dialog. */
  onPrint: (html: string) => void;
  /** Called with the full sheet HTML for PDF generation (jsPDF). */
  onDownloadPdf: (html: string) => void;
  /** Present on desktop → shows the thermal label-printer section. */
  directPrint?: DirectLabelPrint;
  busy?: boolean;
}) {
  const [previewIndex, setPreviewIndex] = React.useState(0);
  const [advancedOpen, setAdvancedOpen] = React.useState(false);

  // Per-dialog print settings (reset from saved on open)
  const [printSettings, setPrintSettings] = React.useState<LabelPrintSettings>(
    () => directPrint?.savedSettings ?? { ...DEFAULT_LABEL_PRINT_SETTINGS },
  );

  React.useEffect(() => {
    if (open) {
      setPreviewIndex(0);
      setAdvancedOpen(false);
      if (directPrint) setPrintSettings(directPrint.savedSettings);
    }
  }, [open, directPrint]);

  function updateSetting<K extends keyof LabelPrintSettings>(key: K, value: LabelPrintSettings[K]) {
    setPrintSettings((prev) => ({ ...prev, [key]: value }));
  }

  function handleSaveSettings() {
    directPrint?.onSaveSettings(printSettings);
  }

  function handleResetDefaults() {
    setPrintSettings({ ...DEFAULT_LABEL_PRINT_SETTINGS });
  }

  function handlePrint() {
    directPrint?.onPrint(printSettings);
  }

  const first = labels[previewIndex] ?? labels[0];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <Tag className="h-5 w-5" />
            </div>
            <div>
              <DialogTitle>Print product labels</DialogTitle>
              <DialogDescription>
                {labels.length} label{labels.length !== 1 ? "s" : ""} · {copies} copy
                {copies !== 1 ? "ies" : ""} · 101 × 15 mm thermal label
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <div className="space-y-4">
          {/* Label preview — matches thermal label aspect ratio (101:15 ≈ 6.7:1). */}
          <div className="flex items-center justify-center rounded-lg border bg-muted/40 p-4">
            <div className="overflow-hidden rounded-md bg-white shadow-sm" style={{ width: "390px", height: "58px" }}>
              {first ? (
                <div
                  style={{ transform: "scale(0.95)", transformOrigin: "center", width: "390px", height: "58px" }}
                  dangerouslySetInnerHTML={{ __html: renderLabelMarkupHTML(first) }}
                />
              ) : (
                <div className="flex h-full items-center justify-center text-xs text-muted-foreground">
                  No label data
                </div>
              )}
            </div>
          </div>

          {labels.length > 1 && (
            <div className="flex items-center justify-center gap-1.5">
              {labels.map((l, i) => (
                <button
                  key={l.productId}
                  type="button"
                  onClick={() => setPreviewIndex(i)}
                  title={l.productName}
                  className={cn(
                    "h-2 w-6 rounded-full transition-colors",
                    i === previewIndex ? "bg-primary" : "bg-muted hover:bg-muted-foreground/40",
                  )}
                  aria-label={`Preview label ${i + 1}`}
                />
              ))}
            </div>
          )}

          {/* Direct thermal label printer (desktop) */}
          {directPrint && (
            <div className="space-y-2 rounded-lg border border-primary/25 bg-primary/5 p-3">
              <div className="flex items-center gap-2">
                <Usb className="h-4 w-4 text-primary" />
                <p className="text-sm font-medium">Label printer (direct)</p>
              </div>
              <div className="flex items-center gap-2">
                <Select
                  value={directPrint.selected ?? ""}
                  onValueChange={directPrint.onSelect}
                  disabled={directPrint.loading || directPrint.printers.length === 0}
                >
                  <SelectTrigger className="h-8 w-full text-xs">
                    <SelectValue
                      placeholder={
                        directPrint.loading
                          ? "Looking for printers…"
                          : directPrint.printers.length === 0
                            ? "No label printers found"
                            : "Choose printer"
                      }
                    />
                  </SelectTrigger>
                  <SelectContent>
                    {directPrint.printers.map((p) => (
                      <SelectItem key={p.name} value={p.name}>
                        {p.name}
                        {p.isDefault ? " (default)" : ""}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8 shrink-0"
                  onClick={directPrint.onRefresh}
                  disabled={directPrint.loading}
                  aria-label="Refresh printer list"
                >
                  <RefreshCw className={cn("h-3.5 w-3.5", directPrint.loading && "animate-spin")} />
                </Button>
              </div>
              {directPrint.error ? (
                <p className="text-xs text-destructive">{directPrint.error}</p>
              ) : (
                <p className="text-xs text-muted-foreground">
                  Prints TSPL2 commands straight to the thermal printer — native barcodes,
                  no print dialog. Printer and label size are set in Settings → Printing.
                </p>
              )}

              {/* Advanced TSPL2 settings */}
              <div>
                <button
                  type="button"
                  className="flex w-full items-center justify-between rounded border bg-background/60 px-3 py-1.5 text-xs font-medium text-muted-foreground hover:bg-background/80 transition-colors"
                  onClick={() => setAdvancedOpen((v) => !v)}
                >
                  <span>Advanced TSPL2 settings</span>
                  {advancedOpen ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
                </button>
                {advancedOpen && (
                  <div className="mt-2 space-y-3 rounded border bg-background/40 p-3">
                    {/* Direction */}
                    <div className="grid grid-cols-2 gap-3">
                      <div className="space-y-1">
                        <label className="text-[11px] font-medium text-muted-foreground" htmlFor="lbl-direction">Direction</label>
                        <Select
                          value={String(printSettings.direction)}
                          onValueChange={(v) => updateSetting("direction", Number(v) as 0 | 1)}
                        >
                          <SelectTrigger id="lbl-direction" className="h-8 text-xs">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="0">DIRECTION 0 (Y from top)</SelectItem>
                            <SelectItem value="1">DIRECTION 1 (Y from bottom)</SelectItem>
                          </SelectContent>
                        </Select>
                        <p className="text-[10px] text-muted-foreground">
                          0 = origin at top-left (default). 1 = origin at bottom-left. Try both if labels split.
                        </p>
                      </div>

                      {/* HRI */}
                      <div className="space-y-1">
                        <label className="text-[11px] font-medium text-muted-foreground" htmlFor="lbl-hri">Barcode digits (HRI)</label>
                        <Select
                          value={String(printSettings.hri)}
                          onValueChange={(v) => updateSetting("hri", Number(v) as 0 | 1 | 2 | 3)}
                        >
                          <SelectTrigger id="lbl-hri" className="h-8 text-xs">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="0">Hidden</SelectItem>
                            <SelectItem value="1">Left of barcode</SelectItem>
                            <SelectItem value="2">Center below</SelectItem>
                            <SelectItem value="3">Right of barcode</SelectItem>
                          </SelectContent>
                        </Select>
                        <p className="text-[10px] text-muted-foreground">
                          Show digits below the barcode bars. Hidden saves space.
                        </p>
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                      {/* GAP */}
                      <div className="space-y-1">
                        <label className="text-[11px] font-medium text-muted-foreground" htmlFor="lbl-gap">Gap (mm)</label>
                        <input
                          id="lbl-gap"
                          type="number"
                          min={0}
                          max={10}
                          step={0.5}
                          value={printSettings.gapMm}
                          onChange={(e) => updateSetting("gapMm", Number(e.target.value) || 0)}
                          className="flex h-8 w-full rounded-md border bg-background px-2 text-xs"
                        />
                        <p className="text-[10px] text-muted-foreground">
                          0 = continuous (no gap). 2 = standard die-cut. Try 0 if labels split.
                        </p>
                      </div>

                      {/* CODEPAGE */}
                      <div className="space-y-1">
                        <label className="text-[11px] font-medium text-muted-foreground" htmlFor="lbl-codepage">Codepage</label>
                        <Select
                          value={printSettings.codepage}
                          onValueChange={(v) => updateSetting("codepage", v)}
                        >
                          <SelectTrigger id="lbl-codepage" className="h-8 text-xs">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="UTF-8">UTF-8</SelectItem>
                            <SelectItem value="USA">USA (ASCII)</SelectItem>
                            <SelectItem value="UK">UK</SelectItem>
                            <SelectItem value="HEX8859-1">ISO 8859-1</SelectItem>
                            <SelectItem value="HEX8859-15">ISO 8859-15</SelectItem>
                          </SelectContent>
                        </Select>
                        <p className="text-[10px] text-muted-foreground">
                          ASCII labels work on any codepage. UTF-8 if unsure.
                        </p>
                      </div>
                    </div>

                    <div className="flex items-center gap-2">
                      <Button variant="ghost" size="sm" className="h-7 text-xs" onClick={handleResetDefaults}>
                        <RotateCcw className="mr-1 h-3 w-3" /> Reset defaults
                      </Button>
                      <Button variant="outline" size="sm" className="h-7 text-xs" onClick={handleSaveSettings}>
                        Save to device
                      </Button>
                    </div>
                  </div>
                )}
              </div>

              <Button
                className="w-full"
                onClick={handlePrint}
                disabled={
                  directPrint.busy ||
                  busy ||
                  labels.length === 0 ||
                  !directPrint.selected ||
                  directPrint.printers.length === 0
                }
              >
                <Printer className="h-4 w-4" />
                {directPrint.busy ? "Printing…" : `Print ${copies} label${copies !== 1 ? "s" : ""} to ${directPrint.selected ?? "printer"}`}
              </Button>
            </div>
          )}

          {/* Copies stepper */}
          <div className="flex items-center justify-between rounded-lg border p-3">
            <div>
              <p className="text-sm font-medium">Number of copies</p>
              <p className="text-xs text-muted-foreground">
                Each copy adds one physical label to the sheet.
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="icon"
                className="h-8 w-8"
                onClick={() => onCopiesChange(Math.max(1, copies - 1))}
                disabled={copies <= 1}
                aria-label="Fewer copies"
              >
                <Minus className="h-4 w-4" />
              </Button>
              <span className="w-10 text-center text-sm font-semibold tabular-nums">{copies}</span>
              <Button
                variant="outline"
                size="icon"
                className="h-8 w-8"
                onClick={() => onCopiesChange(Math.min(100, copies + 1))}
                disabled={copies >= 100}
                aria-label="More copies"
              >
                <Plus className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button
            variant="outline"
            onClick={() => onPrint(renderLabelSheetHtmlFor(labels, copies))}
            disabled={busy || labels.length === 0}
          >
            <Printer className="h-4 w-4" /> Print
          </Button>
          <Button
            onClick={() => onDownloadPdf(renderLabelSheetHtmlFor(labels, copies))}
            disabled={busy || labels.length === 0}
          >
            <FileDown className="h-4 w-4" /> Download PDF
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function renderLabelMarkupHTML(label: ProductLabel): string {
  // Inline preview matching the thermal label layout:
  // LEFT: name (top) + weight (bottom), RIGHT: barcode
  const weight = label.weightMg != null ? formatWeightLocal(label.weightMg) : "";
  const barcodeDigits = label.barcode?.replace(/\D/g, "") ?? "";
  let barcodeBars = "";
  if (barcodeDigits.length >= 12) {
    const pattern = [1,1,1,...barcodeDigits.slice(0, 6).split("").flatMap((d) => { const n = Number(d); const left = [[3,2,1,1],[2,2,2,1],[2,1,2,2],[1,4,1,1],[1,1,3,2],[1,2,3,1],[1,1,1,4],[1,3,1,2],[1,2,1,3],[3,1,1,2]]; return left[n] ?? [2,1,1,2]; }),1,1,1,1,1,...barcodeDigits.slice(6, 12).split("").flatMap((d) => { const n = Number(d); const right = [[2,1,1,2],[1,2,1,2],[2,2,1,1],[1,1,2,2],[2,1,2,1],[1,2,2,1],[1,1,4,1],[1,3,2,1],[2,1,3,1],[1,1,2,3]]; return right[n] ?? [1,1,2,2]; }),1,1,1];
    barcodeBars = `<div style="display:flex;align-items:center;height:90%;gap:0">${pattern.map((w, i) => `<div style="width:${w * 2}px;height:100%;background:${i % 2 === 0 ? "#000" : "transparent"};flex-shrink:0"></div>`).join("")}</div>`;
  } else {
    barcodeBars = `<div style="font-size:7px;color:#999">NO BARCODE</div>`;
  }
  return `<div style="display:flex;align-items:stretch;height:100%;padding:4px 6px;font-family:system-ui,sans-serif;font-weight:600;line-height:1.2">
    <div style="flex:0 0 22%;display:flex;flex-direction:column;justify-content:space-between">
      <div style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:9px">${escHTML(label.productName)}</div>
      <div style="font-size:8px;color:#555;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${weight ? escHTML(weight) : "&nbsp;"}</div>
    </div>
    <div style="flex:1;display:flex;align-items:center;justify-content:center;overflow:hidden">${barcodeBars}</div>
  </div>`;
}

function escHTML(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function formatWeightLocal(mg: number): string {
  const safe = Number.isFinite(mg) ? mg : 0;
  if (safe === 0) return "—";
  const trim = (n: number) => String(Math.round(n * 100) / 100);
  if (safe >= 1_000_000) return `${trim(safe / 1_000_000)} kg`;
  if (safe >= 1000) return `${trim(safe / 1000)} g`;
  return `${safe} mg`;
}

function renderLabelSheetHtmlFor(labels: ProductLabel[], copies: number): string {
  return renderLabelSheetHtml(labels, { copies });
}
