/**
 * Regenerates src/billing/billSeal.ts from <repo>/seal.png — the shop
 * signature stamp embedded as base64 so jsPDF (web/desktop PDF) and
 * expo-print (mobile HTML) can draw it without an asset pipeline.
 *
 * Run from packages/core:  node scripts/embed-seal.mjs
 * (also run it whenever seal.png at the repo root changes)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const repoRoot = join(process.cwd(), "..", "..");
const png = readFileSync(join(repoRoot, "seal.png"));
// Verify dimensions so an accidental re-crop of seal.png fails loudly here
// instead of rendering a squashed stamp on every bill.
const width = png.readUInt32BE(16);
const height = png.readUInt32BE(20);
if (width !== 816 || height !== 294) {
  throw new Error(`seal.png is ${width}x${height}, expected 816x294`);
}

const ts = `/**
 * Shop signature stamp — seal.png (816x294, transparent PNG) as base64.
 * Generated by scripts/embed-seal.mjs — do not edit by hand.
 *
 * The stamp reads "For M/s. JEWELLERY WALA" (top) with a blank signature
 * gap above "PROPRIETOR" (bottom-right). Always preserve the 816:294
 * aspect ratio when placing it, and draw the sign line inside the gap
 * (left 30% .. right 13%, top 72% of the image box).
 */
export const BILL_SEAL_B64 =
  "${png.toString("base64")}";

/** Data-URI form accepted by jsPDF addImage and <img src>. */
export const BILL_SEAL_DATA_URI = \`data:image/png;base64,\${BILL_SEAL_B64}\`;

/** Native pixel size of seal.png — keep width/height proportional to this. */
export const BILL_SEAL_WIDTH = ${width};
export const BILL_SEAL_HEIGHT = ${height};
`;

const out = join(process.cwd(), "src", "billing", "billSeal.ts");
writeFileSync(out, ts);
console.log(`wrote ${out} (${png.length} bytes png -> ${ts.length} bytes ts)`);
